### ISSUE TITLE
[Suggestion] Readme 

### ISSUE THREAD

**Issue by Trle94** [mehdibo/Codeigniter-recaptcha#3]
Hello, its not an issue, more like an update and suggestion to readme documentation.

1. Add somewhere in documentation that users need to add following line in template:
`<script src="https://www.google.com/recaptcha/api.js" async defer></script>` 
Even better would be if you insert on library file after following line: `  // Close the box
        $box .= '></div>`  

I mean yeah we can all add it in header, but why should we add to all pages js script when we do not want to use on all pages recaptcha, so either add on pages you want to use recaptcha manually or edit library as I suggested.

**Comment by mehdibo** [comment]
> Add somewhere in documentation that users need to add following line in template

The "users" are developers, they should know that if you want to use the reCAPTCHA you need the JS file (as stated by the Google's documentation)

> Even better would be if you insert on library file after following line: // Close the box $box .= '></div>

By doing that you will force the use of the script tag inside the body, which is not a good idea because a lot of developers (including myself) like to separate the JS files from the body/code
